# Change these first
owner: Cosmic-Ray-Station # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Cosmicrays.oulu.fi
    url: https://cosmicrays.oulu.fi
  - name: Gle.oulu.fi
    url: https://gle.oulu.fi
  - name: Cosmicrays Data Request
    url: https://cosmicrays.oulu.fi/webform/onlinequery.cgi?station=DOMC&startday=17&startmonth=02&startyear=2022&starttime=00%3A00&endday=17&endmonth=07&endyear=2022&endtime=00%3A00&resolution=Automatic+choice&outputmode=default
 
status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CRM Uptime Monitor
  introTitle: "Cosmic Ray Station Oulu - Uptime monitor"
  introMessage: Uptime tracker and history of downtimes for the Cosmic Ray Station Oulu web server.
  navbar:
    - title: Status
      href: /
    - title: Cosmic Ray Station
      href: https://cosmicrays.oulu.fi

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
